[package]
name = "taskui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
crossterm = "0.28"
grep-matcher = "0.1"
libc = "0.2"
grep-regex = "0.1"
grep-searcher = "0.1"
nucleo-matcher = "0.3"
portable-pty = "0.8"
ratatui = "0.29"
strip-ansi-escapes = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml_ng = "0.10.0"
notify = "8.2.0"
